name: CI/CD workflow 
on: workflow_call
jobs:
  deployJob:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the code
       uses: actions/checkout@v4
     - name: Download Java and Maven
       uses: actions/setup-java@v4
       with: 
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
     - name: Install docker 
       uses: docker/setup-buildx-action@v3
     - name: Build the code 
       run: mvn package
     - name: Login to dockerhub
       uses: docker/login-action@v3
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build Image and push to dockerhub 
       uses: docker/build-push-action@v6
       with: 
        context: .
        push: true 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/myprojectimage:latest
